### ISSUE TITLE
Update Gradle

### ISSUE THREAD

**Issue by Abdelsattar** [Abdelsattar/NaVIGATION#1]
Please update your gradle to maintain the latest things

**Comment by AhmedBadrSayed** [comment]
I need to solve location problem asap so i don't have so much time to implement the update now

**Comment by Abdelsattar** [comment]
ok try to update it in the background as you are working if it can't so after solve this problem you will need to update it before any other tasks 
and after updating push the code and close this issue :thumbsup: :thumbsup:

**Comment by AhmedBadrSayed** [comment]
android studio updated to 2.3.1
